name: static_shock
description: A static site generator for Dart.
version: 0.0.13
repository: https://github.com/flutter-bounty-hunters/static_shock

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  dart_rss: ^3.0.3
  fbh_front_matter: ^0.0.1
  github: ^9.24.0
  http: ^1.2.1
  image: ^4.2.0
  intl: ^0.19.0
  jinja: ^0.6.0
  markdown: ^7.0.2
  mason_logger: ^0.2.5
  path: ^1.8.3
  pub_updater: ^0.4.0
  puppeteer: ^3.16.0
  sass: ^1.62.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
