name: static_shock
description: A static site generator for Dart.
version: 0.0.1
repository: https://github.com/flutter-bounty-hunters/static_shock

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  front_matter:
    git:
      url: https://github.com/maks/front-matter.git
      ref: null-safety
  jinja: ^0.4.2
  markdown: ^7.0.2
  mason_logger: ^0.2.5
  path: ^1.8.3
  sass: ^1.62.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
