name: static_shock
description: A static site generator for Dart.
version: 0.0.1-dev.2
repository: https://github.com/flutter-bounty-hunters/static_shock

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  fbh_front_matter: ^0.0.1
  html: ^0.15.4
  jinja: ^0.4.2
  markdown: ^7.0.2
  mason_logger: ^0.2.5
  path: ^1.8.3
  pub_updater: ^0.3.0
  sass: ^1.62.1
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
