name: static_shock_cli
description: CLI for Static Shock - a static site generator, written in Dart.
version: 0.0.3
repository: https://github.com/flutter-bounty-hunters/static_shock

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  shock: static_shock_cli

dependencies:
  static_shock: ^0.0.1

  args: ^2.4.0
  cli_completion: ^0.3.0
  mason: ^0.1.0-dev.49
  mason_logger: ^0.2.12
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  pub_updater: ^0.4.0
  yaml: ^3.1.2
  watcher: ^1.1.0
  html: ^0.15.4
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.0
  pub_semver: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.5
  build_version: ^2.1.1
  lints: ^3.0.0
  test: ^1.21.0
