name: static_shock_cli
description: CLI for Static Shock - a static site generator, written in Dart.
version: 0.0.1-dev.2
repository: https://github.com/flutter-bounty-hunters/static_shock

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  shock: static_shock_cli

dependencies:
  static_shock: ^0.0.1-dev.2

  args: ^2.4.0
  cli_completion: ^0.3.0
  mason: ^0.1.0-dev.49
  mason_logger: ^0.2.5
  shelf: ^1.4.1
  shelf_static: ^1.1.2

dependency_overrides:
  static_shock:
    path: ../static_shock

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
