name: static_shock_docs
description: Documentation for Static Shock
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  static_shock:
    path: ../static_shock

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
